### PR TITLE
Add zh-cn.yml

### PR DESCRIPTION
**Pull request by LaoshuBaby**
i18n for taginfo
#322

### CODE REVIEW

**Comment by joto** [comment]
Thanks for the translations. I notice that the translations for all the singular/plural pair like "way" and "ways" etc. are the same. Is this correct?

**Comment by LaoshuBaby** [comment]
In Chinese we ususlly don't have difference between prototypes and plurals of nouns. (Some times have, but it is special)
(You can see the ```zh-tw.yml``` to confirm）





------------------&nbsp;Original&nbsp;------------------
From: "Jochen ***@***.***&gt;; 
Date: 2021年4月18日(星期天) 下午3:57
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [taginfo/taginfo] Add zh-cn.yml (#323)





 
Thanks for the translations. I notice that the translations for all the singular/plural pair like "way" and "ways" etc. are the same. Is this correct?

**Comment by LaoshuBaby** [comment]
https://github.com/taginfo/taginfo/blob/4e72b07cbe821a31ce0aedd53333522ee9d59001/web/i18n/zh-tw.yml#L11

For example you can see that, the contributor supaplex is a native speaker of T-Chinese

The ```way``` and ```ways``` is sharing the same word ```路徑```

and I use ```路径``` in S-Chinese version

**Comment by LaoshuBaby** [comment]
I will finish this translation in spare time so the merge can wait for a few time. ♥

**Comment by joto** [comment]
I am merging this now so that we have at least the beginning. You can always add more translations later in new pull requests.

**Pull request merged**
