### PR TITLE
Remove anchors from regular expression routes

### PR DESCRIPTION
**Pull request by tomhughes**
Sinatra 2 anchors implicitly, and will complain if the pattern for a route has explicit anchors.

I think, though I'm not entirely sure, that the anchors are required in Sinatra 1.x, so this might need to be documented properly.

### CODE REVIEW

**Comment by joto** [comment]
I tested it with Sinatra 1.4.7 and it seems fine.

**Comment by ImreSamu** [comment]
I have tested the current master ( Latest commit ffafd73 )  
-  ( with "bundle install"  patch  -> `sinatra (2.0.3)`  )

And I have a small problem with
-  Colon (":") character inside osm keys  [ `addr:street` ; `addr:city` ...]

my guess:  
* something  changed  inside  the `sinatra 2.x.x`

exampe: 
* my local test url : http://127.0.0.1:30002/keys/addr%3Astreet 
* current live system : https://taginfo.openstreetmap.org/keys/addr%3Astreet


## Now I get - http://127.0.0.1:30002/keys/addr%3Astreet 

screenshot from 2018-07-04 02-10-51

## Expected:

screenshot from 2018-07-04 02-17-56

**Comment by joto** [comment]
@ImreSamu  Please open a new issue for new issues instead of reusing something old. If it seems related, link to the other issue.

**Comment by ImreSamu** [comment]
sorry,  I have created -> https://github.com/taginfo/taginfo/issues/235

**Pull request merged**
