### PR TITLE
Do not hide #tools on mobile

### PR DESCRIPTION
**Pull request by simon04**
Level0 editor and overpass turbo permit mobile use.

### CODE REVIEW

**Comment by joto** [comment]
This has been left out on purpose, because I thought not many people will use it and it clutters up the display. We need to do better on mobile screens, but I am not sure this is the way to go.

Do you actually want to use those buttons?

**Comment by simon04** [comment]
For mobile editing using OsmAnd, I wanted to lookup a somewhat rare tag using Taginfo by [searching for its German name](https://taginfo.openstreetmap.org/search?q=abfahrtsmonitor#values) and inspecting the tag combinations on Level0 editor.

**Comment by joto** [comment]
Can we find a better solution that doesn't take up as much screen real estate? Maybe a button that opens a menu?

**Comment by joto** [comment]
I think (1) would overload that menu of the most important sections of the site.

(2) is too large already and also needs some solution. On this particular page/device it seems okay, but the tab headings there will break over several lines if they become just a bit longer.

(3) would bring the tools into the tab area, that's not good, they don't belong in there.

(4) looks like the best solution to me of these options.

But the "Filter: no filter" is also not that important. Maybe we can hide that and the tools all together in a menu?

**Comment by joto** [comment]
Now you moved it for larger screens also?

**Comment by simon04** [comment]
Yes. Having different positions for desktop/mobile would require some JavaScript to be written.

For me, (2) would be the cleanest solution (working for desktop as well as mobile).

I don't want to spend hours on this PR. We can also close it as WONTFIX.

**Comment by joto** [comment]
I think we stil don't have a really good solution, the PR as it currently is, would be a solution for the mobile version, but I don't want to make this harder to use for people with a large screen. UI is hard. If you don't want to keep working on this, we can just leave it open, maybe somebody else has a better idea or I'll find the time to work on it.

**Comment by joto** [comment]
@simon04 I have just deployed a solution for this problem with a pop-down menu. Can you see whether this works for you?

**Comment by simon04** [comment]
Thank you! It's nicely working for https://taginfo.openstreetmap.org/keys/railway, but not shown on https://taginfo.openstreetmap.org/tags/railway=tram_stop

**Comment by joto** [comment]
Uh. Forgot to activate it for tags and relations. Works now.

**Comment by simon04** [comment]
Great, thank you.

The "Level0 Editor" link is not working on https://taginfo.openstreetmap.org/tags/ref%3Aat%3Abda=25058 (since `href="#"`)

**Comment by joto** [comment]
Fixed now.

**Comment by simon04** [comment]
Great, thank you. Closing this obsolete PR now…

**Pull request closed without merging**
